# Permalinks
permalink:           pretty

# Setup
title:               Kaya's blog
tagline:             A Data Science Blog
url:                 http://wkaya.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kaya Wu
  url:               https://url.com
  email:             wkaya@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/wkaya

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
